dataset:
  data_path: data/
  dev_ratio: 0.2
  has_node_feat: false
  is_overwrite_precompute: false
  is_sample_subgraph: true
  is_save_split: false
  loader_name: GRANData
  name: PTC_lattice_graph
  node_order: DFS
  num_fwd_pass: 1
  num_subgraph_batch: 2
  train_ratio: 0.8
device: cuda:0
exp_dir: exp/GRAN
exp_name: GRANMixtureBernoulli_PTC_lattice_graph_2022-Jun-24-12-39-24_9769
gpus:
- 0
model:
  block_size: 1
  dimension_reduce: true
  edge_weight: 1.0
  embedding_dim: 512
  has_attention: true
  hidden_dim: 512
  is_sym: true
  max_num_nodes: 500
  name: GRANMixtureBernoulli
  num_GNN_layers: 7
  num_GNN_prop: 1
  num_canonical_order: 1
  num_mix_component: 20
  sample_stride: 1
run_id: '9769'
runner: GranRunner
save_dir: exp/GRAN/GRANMixtureBernoulli_PTC_lattice_graph_2022-Jun-24-12-39-24_9769
seed: 1234
test:
  batch_size: 20
  better_vis: true
  dataset_name: PTC_lattice_graph
  is_single_plot: false
  is_test_ER: false
  is_vis: true
  num_test_gen: 408
  num_vis: 20
  num_workers: 0
  test_model_dir: exp/GRAN/GRANMixtureBernoulli_PTC_lattice_graph_2022-Jun-24-12-39-24_9769
  test_model_name: model_snapshot_0049000.pth
  vis_num_row: 5
train:
  batch_size: 16
  display_iter: 10
  is_resume: false
  lr: 0.0001
  lr_decay: 0.1
  lr_decay_epoch:
  - 100000000
  max_epoch: 50000
  momentum: 0.9
  num_workers: 16
  optimizer: Adam
  resume_dir: null
  resume_epoch: 5000
  resume_model: model_snapshot_0005000.pth
  shuffle: true
  snapshot_epoch: 1000
  valid_epoch: 50
  wd: 0.0
use_gpu: true
use_horovod: false
